### ISSUE TITLE
Axis labels not working for me

### ISSUE THREAD

**Issue by CorySimon** [marcharper/python-ternary#29] opened 2015-10-27 18:24 UTC
Great tool. I will cite this in my paper! Oddly,

    tax.left_axis_label("Left label $\\alpha^2$", fontsize=fontsize)
    tax.right_axis_label("Right label $\\beta^2$", fontsize=fontsize)
    tax.bottom_axis_label("Bottom label $\\Gamma - \\Omega$", fontsize=fontsize)

do not work for me...

EDIT: I just needed to type:

    tax._redraw_labels()

but it would be good to not have to do this.

**Comment by marcharper** [comment] 2015-10-27 18:28
I'm glad that you find the library useful.

Can you post a full example where the labels fail to render? I'll see if I can post a quick patch.

**Comment by CorySimon** [comment] 2015-10-27 18:30
I used exactly the code in the README, under `Drawing lines`.

**Comment by marcharper** [comment] 2015-10-27 18:35
Huh. The Readme.md example works unaltered for me, as does running `examples.py` that the readme draws from. So I guess I need more information, perhaps your matplotlib version (I have 1.4.2 installed), and anything else that may be relevant.

**Comment by CorySimon** [comment] 2015-10-27 18:42
I am using Matplotlib '1.4.3'. Perhaps that is why?

**Comment by marcharper** [comment] 2015-11-07 23:41
I'm unable to reproduce this, and the axis labels work on matplotlib 1.5.0. So I'm closing this issue; if anyone else has this issue please reopen.

**Closed by marcharper** 2015-11-07 23:41 UTC
